### ISSUE TITLE
No package 'cairo' found on npm install

### ISSUE THREAD

**Issue by Jorybraun** [SumiMakito/Awesome-qr.js#28]

**Comment by Jorybraun** [comment]
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/jory.braun/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/jory.braun/.nvm/versions/node/v8.11.3/bin/node" "/Users/jory.braun/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jory.braun/Documents/code/qr_code_api/node_modules/canvas
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN qr_code_api@1.0.0 No description
npm WARN qr_code_api@1.0.0 No repository field.

**Comment by walkerrandolphsmith** [comment]
Is this still the case on 1.2.1 as of https://github.com/SumiMakito/Awesome-qr.js/commit/f3ed53331c51223427e498f3e5802770207e7396? Now that this package relies on pre-built canvas it might be a moot point..?

**Comment by bmaclean** [comment]
I think the root issue is just that 1.2.1 doesn't appear to be published to npm.
